src/webapp/user/routes.py
from flask import Blueprint, request, render_template, redirect, jsonify, url_for
from webapp.database import db, Grein, Verification, UserModel, login, Stubbi
import uuid
from webapp.serve_content import serve_content, query_latest_content, sort_unionQuery
from webapp.verify import send_verification
from flask_login import login_required, current_user, login_user, logout_user
from .utils import set_vangi
from webapp.verify import send_verification, verify, whitelist
from webapp.settings import app_config

user_bp = Blueprint(
    'user', 
    __name__, 
    url_prefix='', 
    static_folder='user_static', 
    template_folder='templates'
)


## LOAD SETTINGS FROM SETTINGS YAML FILE
app_config = app_config()


@user_bp.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(f'/@{current_user.vangi}')

    if request.method == 'POST':
        email = request.form['email']
        fornavn = request.form['fornavn']
        efturnavn = request.form['efturnavn']
        telefon = request.form['telefon']
        password = request.form['password']

        if UserModel.query.filter_by(email=email).first():
            return ('Email finst longu')
        if UserModel.query.filter_by(telefon=telefon).first():
            return ('telefon finst longu')
        # generate id with 10 Characters
        uuid_obj = uuid.uuid4()
        user_id = uuid_obj.hex[:10]
        

        vangi = set_vangi([fornavn,efturnavn], True)
        
        user = UserModel(
            user_id = user_id,
            email=email,
            fornavn=fornavn,
            efturnavn=efturnavn,
            telefon=telefon,
            vangi=vangi)

        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        if app_config["verifyPhone"]:
            send_verification(user_id, "both", [telefon, email])
            return render_template('verify.html', session_id=user_id, telefon=telefon)
        else: 
            whitelist(user_id)
            return redirect(url_for('user.login'))
    else:
        return render_template('register.html')

@user_bp.route('/ritainn', methods = ['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect('/profilur')
    if request.method == 'POST':
        email = request.form['email']
        user = UserModel.query.filter_by(email = email).first()
        if user is not None and user.check_password(request.form['password']):
            login_user(user)
            return redirect('/')
    return render_template('ritainn.html')

@user_bp.route('/logout')
def logout():
    logout_user()
    return redirect('/')

@user_bp.route('/um_meg', methods=['POST', 'GET'])
@login_required
def um_meg():
    if request.method == 'POST':
        form_data = request.form  # get the form data

        for key in form_data:
            value = form_data[key]
            print(f"{key}: {value}")
            if key == 'fornavn':
                current_user.fornavn = value
            elif key == 'efturnavn':
                current_user.efturnavn = value
            elif key == 'stovnur':
                current_user.stovnur = value
            elif key == 'telefon':
                if app_config["verifyPhone"]:
                    pass
                else: 
                    current_user.telefon = value
                current_user.telefon = value
            elif key == 'email':
                if app_config["verifyPhone"]:
                    pass
                else: 
                    current_user.email = value
            elif key == 'vangi':
                if set_vangi(value):
                    current_user.vangi = value
                else:
                    return jsonify({'success': False, 'error': "Prøva okkurt annað, hetta er longu tykið"}), 200

            else: return jsonify({'success': False, 'error': "form not found"}), 200
        db.session.commit()
        return jsonify({'success': True}), 200
    else:
        user = UserModel.query.get(current_user.user_id)
        return render_template('um_meg.html',user=user)

@user_bp.route("/um_meg/open")
@login_required
def um_meg_navn():
    target_id = request.args.get('id')
    user = UserModel.query.get(current_user.user_id)
    return render_template('um_meg-open.html', target_id=target_id, user=user)


@user_bp.route('/@<string:vangi>')
def brukari(vangi):
    user = UserModel.query.filter(UserModel.vangi == vangi).join(Verification).filter(Verification.status == 'verified').first()
    user_owner = False
    if user:
        if current_user.is_authenticated:
            if current_user.user_id == user.user_id:
                user_owner = True
        article_count = Grein.query.join(UserModel).filter(UserModel.user_id == Grein.author_id).order_by(Grein.created_stamp.desc()).count()
        user_content = query_latest_content(user.user_id)
        sorted_user_content = sort_unionQuery(user_content)
        content = serve_content(sorted_user_content)
        return render_template('brukari.html',art=content, user=user, user_owner=user_owner)
    else:
        return render_template('error.html', error=f'{vangi} finst ikki')

src/webapp/user/templates/brukari.html
{% extends 'base.html' %}

{% block head %}
        <title>Profilur</title>
        <link rel="stylesheet" href="{{ url_for('user.static', filename='brukari.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
        <link rel="stylesheet" href="{{ url_for('content.static', filename='article.css') }}">
{% endblock %}

{% block left %}
{% endblock %}




{% block banner %}



<div class="banner">
</div>

{% endblock %}

{% block content %}

<div class="brukari">
    <div class="brukari-content">
        <div class="profile-picture">
            {% if user.picture_path %}
            <img src="{{ url_for('static', filename='uploads/' + 'large-' + user.picture_path) }}" alt="">
            {% else %}
            <img src="{{ url_for('static', filename='login.png') }}" alt="">
            {% endif %}
        </div>
        <div class="tekstur">
            <div class="navn">
                {% if user.fornavn %}
                <p>{{ user.fornavn }} {% if user.efturnavn %}{{ user.efturnavn }}{% endif %}</p>
                {% endif %}
            </div>
            <div class="vangi">
                <a href="/@{{user.vangi}}">@{{ user.vangi }}</a>
            </div>

            {% if user.stovnur %}
            <div class="identity">
                <p>{{ user.stovnur }}</p>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="fylg-container">
        <button class="fylg-knappur">Fylg Mær</button>
        <div class="stats-container">
            <div class="fylgjarir">
                <p>5 Fylgjarir</p>
            </div>
            <div class="vertical-line"></div>
            <div class="fylgir">
                <p>10 Fylgir</p>
            </div>
        </div>
    </div>
</div>
{% if user_owner %}
<div class="post">
    <img src="{{ url_for('user.static', filename='pluss.png')}}"></img>
</div>
<script src="{{ url_for('post.static', filename='vel-postform.js') }}"></script>
{% endif %}
{% if art %}
{% include "base-prev.html" %}
                <div class="floatingBox-Placeholder" id="placeholder"></div>
                <script src="{{ url_for('content.static', filename='onBottom.js') }}"></script>
                <script src="{{ url_for('content.static', filename='click-floatingBox.js') }}"></script>
{% endif %}
{% endblock %}

src/webapp/user/templates/register.html
{% extends 'base.html' %}

{% block head %}
        <title>Upprætta</title>
        <link rel="stylesheet" href="{{ url_for('user.static', filename='register.css') }}">
{% endblock %}

{% block content %}
<div class="main-register">
<form action="" method = "POST">
    <p>Post Addressa <input type = "email" name = "email" /></p>
    <p>Fornavn <input type = "fornavn" name = "fornavn" /></p>
    <p>Efturnavn <input type = "efturnavn" name = "efturnavn" /></p>
    <p>Telefon nummar <input type = "text" name = "telefon" /></p>
    <p>Loyniorð<input type = "password" name = "password" /></p>
    <p>Upprætta<input type = "submit" value = "Submit" /></p>
</form>

<h3>Hevur tú longu konto?</h3><br>
<h3><a href ="{{url_for('user.login')}}">Rita inn</a></h3>
</div>

{% endblock %}

src/webapp/user/templates/ritainn.html
{% extends 'base.html' %}

{% block head %}
        <title>Rita inn</title>
        <link rel="stylesheet" href="{{ url_for('user.static', filename='ritainn.css') }}">
{% endblock %}

{% block content %}
<div class="main-ritainn">
    
    
    <form action="" method = "POST">
        <p>Post addressa<input type = "email" name = "email" /></p>
        <p>Loyniorð<input type = "password" name = "password" /></p>
        <p>Rita inn<input type = "submit" value = "Submit" /></p>
    </form>
    <h3>Manglar tú konto?</h3>
    <h3><a href = "{{url_for('user.register') }}">Upprætta teg her</a></h3>
</div>
{% endblock %}

src/webapp/user/templates/um_meg-open.html
<div class="edit-open" id="navn">
    <div class="nøvn">
        <form class="um_meg_form">
            <p>Fornavn <input type = "fornavn" name = "fornavn" value="{{ user.fornavn }}" /></p>
            <p>Efturnavn <input type = "efturnavn" name = "efturnavn" value="{{ user.efturnavn }}"/></p>
            <div class="knappar">
                <div class="goymKnappurDiv">
                    <button class="goymKnappur" type="submit" >Goym broytingar</button>
                </div>
                <div class="closeKnappurdiv">
                    <button class="closeKnappur" type="submit" >Lat aftur</button>
                </div>
            </div>
        </form>
    </div>
    <div class="message"><p></p></div>
</div>

<div class="edit-open" id="stovnur">
    <form class="um_meg_form">
        <p>stovnur/felagskapur <input type = "text" name = "stovnur" value="{{ user.stovnur }}" /></p>
        <div class="knappar">
            <div class="goymKnappurDiv">
                <button class="goymKnappur" type="submit" >Goym broytingar</button>
            </div>
            <div class="closeKnappurdiv">
                <button class="closeKnappur" type="submit" >Lat aftur</button>
            </div>
        </div>
    </form>
    <div class="message"><p></p></div>
</div>

<div class="edit-open" id="telefon">
    <p>Fyri at broyta telefon nummar, er neyðugt at vátta nýggja nummari.<br>
        Hetta kann gerast við vátta kodu sum blívur send til nýggja nummari.
    </p>
    <form class="um_meg_form">
        <p>Telefon nummar <input type = "text" name = "telefon" value="{{ user.telefon }}"/></p>
        <div class="knappar">
            <div class="goymKnappurDiv">
                <button class="goymKnappur" type="submit" >Goym broytingar</button>
            </div>
            <div class="closeKnappurdiv">
                <button class="closeKnappur" type="submit" >Lat aftur</button>
            </div>
        </div>
    </form>
    <div class="message"><p></p></div>
</div>
<div class="edit-open" id="email">
    <form class="update-email">
        <p>Post adressa <input type = "text" name = "email" value="{{ user.email }}"/></p>
        <div class="knappar">
            <div class="goymKnappurDiv">
                <button class="goymKnappur" type="submit" >Goym broytingar</button>
            </div>
            <div class="closeKnappurdiv">
                <button class="closeKnappur" type="submit" >Lat aftur</button>
            </div>
        </div>
    </form>
    <div class="message"><p></p></div>
</div>
<div class="edit-open" id="vangi">
    <form class="um_meg_form">
        <p>Vanga addressa <input type = "text" name = "vangi" value="{{ user.vangi }}"/></p>
        <div class="knappar">
            <div class="goymKnappurDiv">
                <button class="goymKnappur" type="submit" >Goym broytingar</button>
            </div>
            <div class="closeKnappurdiv">
                <button class="closeKnappur" type="submit" >Lat aftur</button>
            </div>
        </div>
    </form>
    <div class="message"><p></p></div>
</div>
<div class="edit-open" id="mynd">
    <form id="upload-form">
        <label for="file">Vel eina vangamynd:</label><br>
        <input type="hidden" name="session_id" value="{{user.user_id}}">
        <input type="file" name="picture" >
        <button class="btn" type="submit" >Upload</button><br>
        <script src="{{ url_for('static', filename='upload.js') }}"></script>
        <div id="message"></div>
    </form>
    {% if user.picture_path %}
    <img id="large-image-preview" src="{{ url_for('static', filename='uploads/' + 'large-' + user.picture_path) }}" alt="">
    {% else %}
    <img id="large-image-preview" src="" alt="">
    {% endif %}
    <div class="closeKnappurdiv">
        <button class="closeKnappur" type="submit" >Lat aftur</button>
    </div>
    <div class="message"><p></p></div>
</div>
<div class="edit-open" id="loyniord">
    <p>ger ein knapp her til send email við password change logic.</p>
    <div class="closeKnappurdiv">
        <button class="closeKnappur" type="submit" >Lat aftur</button>
    </div>
    <div class="message"><p></p></div>
</div>

src/webapp/user/templates/um_meg.html
{% extends 'base.html' %}
{% block head %}
        <title>Um meg</title>
        <link rel="stylesheet" href="{{ url_for('user.static', filename='um_meg.css') }}">
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}


<div class="main-um_meg">

    <div class="editables">
        <div class="edit" id="navn">
            <div class="edit-box">
                <span class="edit-item">navn:</span> <span class="edit-result"> {{user.fornavn}} {{user.efturnavn}}</span> <br>
            </div>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <div class="edit" id="stovnur">
            <div class="edit-box">
                <span class="edit-item">stovnur/felagskapur: </span><span class="edit-result"> {{user.stovnur}}</span>
            </div>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <div class="edit" id="telefon">
            <div class="edit-box">
                <span class="edit-item">Telefon Nummar:</span> <span class="edit-result"> {{ user.telefon}}</span>
            </div>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <div class="edit" id="email">
            <div class="edit-box">
                <span class="edit-item">Post adressa:</span> <span class="edit-result"> {{ user.email}}</span>
            </div>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <div class="edit" id="vangi">
            <div class="edit-box">
                <span class="edit-item">vangi:</span> <span class="edit-result"> {{ user.vangi}}</span>
            </div>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <div class="edit" id="mynd">
            <span class="edit-item">Dagfør Vangamynd</span>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <div class="edit" id="loyniord">
            <div class="edit-box">
                <span class="edit-item">Broyt Loyniorð</span>
            </div>
            <div class="edit-link"><span>broyt</span></div>
        </div>
        <script src="{{ url_for('user.static', filename='editbox.js') }}"></script>
    </div>

</div>
{% endblock %}